###################################################################################################################
#  ________         __                                 ______                       __                            #        
# /        |       /  |                               /      \                     /  |                           #
# $$$$$$$$/______  $$ |  _______   ______   _______  /$$$$$$  |  ______    ______  $$ |   __   ______    ______   #
# $$ |__  /      \ $$ | /       | /      \ /       \ $$ \__$$/  /      \  /      \ $$ |  /  | /      \  /      \  #
# $$    | $$$$$$  |$$ |/$$$$$$$/ /$$$$$$  |$$$$$$$  |$$      \ /$$$$$$  |/$$$$$$  |$$ |_/$$/ /$$$$$$  |/$$$$$$  | #
# $$$$$/  /    $$ |$$ |$$ |      $$ |  $$ |$$ |  $$ | $$$$$$  |$$    $$ |$$    $$ |$$   $$<  $$    $$ |$$ |  $$/  #
# $$ |   /$$$$$$$ |$$ |$$ \_____ $$ \__$$ |$$ |  $$ |/  \__$$ |$$$$$$$$/ $$$$$$$$/ $$$$$$  \ $$$$$$$$/ $$ |       #
# $$ |   $$    $$ |$$ |$$       |$$    $$/ $$ |  $$ |$$    $$/ $$       |$$       |$$ | $$  |$$       |$$ |       #
# $$/     $$$$$$$/ $$/  $$$$$$$/  $$$$$$/  $$/   $$/  $$$$$$/   $$$$$$$/  $$$$$$$/ $$/   $$/  $$$$$$$/ $$/        #
#                                                              
# Hello, my name is Falcon_Seeker, but my friends call me Falcon. I can code custom spigot
# plugins for your server, MythicalQuest. Here is my pricing.
#
# 1st Plugin - Free
# All Other Plugins - $1/10kb 
#
# However, depending on the complexity and time taken, prices might lower or higher.
#
# If you would like to see my spigot page, (NOTE: It is old the plugins on spigot have
# not recently been updated) although I have worked on a few succesful servers might I say.
# Take for instance voxtillity, a (now dead) server that once had a playerbase of 70.
#
# If you are interested in my services, please contact me or join my discord! 
# https://discord.gg/r8ezrN4   
#
#
#                                                                                                         #
# * This plugin supports PlaceholderAPI but will work without it.                                                 #
# * You are not allowed, by any terms, to redistribute, modify, or copy and of the code contained in this or any  #
#   other of my plugins.                                                                                          #
#                                                                                                                 #
# PLACEHOLDERS:                                                                                                   #
#        %thepit_nam e% - displays the player's name                                                               #
#        %thepit_level% - shows the play's level with prestige                                                    #
#        %thepit_xp% - the amount of xp until the player reaches the next level                                   #
#        %thepit_stat% - returns wether or not the player is in combat.                                           #
#        %thepit_date% - returns the current date in the format day/month/year                                    #
#        %thepit_gold% - shows how much currency the player has (NOT VAULT SUPPORTED)                             #
#                                                                                                                 #
# * Permissions and commands can be found on the plugin page or by typing /thepit help in-game                    #
# * If you have an issue, feel free to contact me on my discord or on spigot.                                     #
#                                                                                                                 #
###################################################################################################################
CombatTag:
  Duration: 5 #How long the combat tag lasts before the player is set to "idling" again
Econ-Enabled: true
Events:
  - 'QUICKMATHS'
#Find a list of materials here: 
Gold:
  Amount: 1 #Amount of gold that drops
  Material: GOLD_INGOT #Material that drops.
  Intervals-In-Seconds: 20
 #Titles and actionbar settings for when the player dies. Set to " " if you do not want that section.
Titles:
  Enabled: true
  Actionbar: ' '
  Title: '&cYOU DIED' #Title shown on death screen
  Subtitle: ' '
  Levelup-Subtitle: '&7%old_level% → %thepit_level%'
  Levelup-Title: '&b&lLEVEL UP!' #Title shown when a player's level upgrades
Levels:
  Exp: 16
#Flickerless scoreboard options. Title is the first line, footer is the last. Refresh rate is how fast the 
#nametags AND scoreboard refresh.
Scoreboard:
  footer: '&ewww.hypixel.net' #Bottom-most line of the scoreboard
  title: '&e&lTHE HYPIXEL PIT' #Upper most line of the scoreboard
  scores:
  - '&7%thepit_date%'
  - ' '
  - '&fLevel: &7%thepit_level%'
  - 'NeededXP: &b%thepit_xp%'
  - ' '
  - 'Gold: &6%thepit_gold%'
  - ' '
  - 'Status: %thepit_stat%'
  - ' '
  RefreshRate: '1' #How fast in seconds the scoreboard reloads
  
#Change the default chat format. Set Enabled to false if you have another custom plugin such as EssentialsChat
#which modifies the chat.
ChatFormat:
  Enabled: true
  Format: '&f%thepit_level% &7%thepit_name% : %message%'
  Nametag: '%thepit_level% '
#Header and footer on the tablist.
Tablist:
  Header: '&bYou are playing on &e&lMC.HYPIXEL.NET'
  Footer: '&ARanks, Boosters & MORE! &c&lSTORE.HYPIXEL.NET'
#Every message sent in-game by ThePit.
Messages:
  DropItem: '&e&lYOU SURE? &7dropping &ethis item &e&lCLICK HERE'
  Fighting: '&cCombat' #Shown on scoreboard when player enters combat
  Idle: '&aIdle' # Shown on scoreboard when player leaves combat
  EventLog: '&6Event' # Shown on scoreboard when an event is triggered
  Unknown: '&cUnknown Command. Type /thepit for help'
  Reload: '&aConfig reloaded.'
  Levelup: '&aYou have leveled up to %thepit_level%.'
  Respawn: '&aYou have respawned.'
  NoPermission: '&cNo permission to use this command!'
  Setgold: '&aLocation added. Type /thepit goldstart to start it.'
  Help: #Not reccomended to change for future reference.
    - '&7----------------&c&l[THEPIT]&7----------------'
    - '&c/thepit - &7Displays this help message'
    - '&c/thepit setgold - &7Sets a spawn location for gold'
    - '&c/thepit goldstart - &7Starts spawning gold.'
    - '&c/thepit reload - &7Reloads the config'
    - '&c/thepit kills - &7Creates hologram of kill stats. '
    - '&c/thepit stats - &7Shows gui of player stats.'
    - '&c/thepit blood - &7GUI where player can select death animations.'
    - '&c/thepit respawn - &7Teleports the player to spawn'
    - '&c/thepit perks - &7Display perks based on prestige.'
    - '&c/thepit levelup - &7Gives the player +1 level.'
    - '&c/thepit stats - &7GUI of player statistics'
    - '&c/gold <Player> <Amount> - &7Built in economy'
    - '&c/protect - &7First click a b'
    - '&c/thepit spawntiems <Player> <Amount> - &7Built in economy'
    - '&c/thepit giveitem <Enchantment> &7Gives a mystic wells item with that enchantment'

Launchpads:
  Material: SLIME_BLOCK
#Events that run every x minutes
Events:
  Start-Message: '&aAN EVENT STARTED!'
  Holo-String: '&eEvent Running!'
  Types:
    QuickMaths:
      Enabled: true
      Message: 'QUICK MATHS HAS STARTED! %f% + %s%'
Blocked-Worlds: #Worlds that the pit is disabled in.
  - 'aa'
  - 'anotherblockedworld'
Tags:
 Default:
  Color: '&d'
 MVP:
  Color: '&d'
 Vip:
  Color: '&6' 
EnchantmentTypes: #All enchantments added by the mystic well.

#PANTS ENCHANTMENTS

  BOOBOO:
    Lore: #Lore added to item when enchantment applied.
    - ' '
    - '&9Boo-boo'
    - '&7Passively regain &c1❤  &7every 5'
    - '&7Seconds'
  CREATIVE:
    Lore:
    - ' '
    - '&9Creative'
    - '&7Spawn with &b16 planks&7. Wood remains for'
    - '&730 seconds. Gain &b+6 blocks &7on kill.' 
  CRICKET:
    Lore:
    - ' '
    - '&9Cricket'
    - '&7 Receive &9-7% &7damage when you or your'
    - '&7victim are standing on grass.' 
  DANGERCLOSE:
    Lore:
    - ' '
    - '&9Danger Close'
    - '&7Gain &eSpeed III &7(6s) when'
    - '&7reaching &c4❤ &7(10s cooldown)'
  EGGS:
    Lore:
    - ' '
    - '&9Eggs'
    - '&7Spawn with &b8 eggs.'
    - '&7Gain &b+8 eggs &7on kill.'
  ELECTROLYTES:
    Lore:
    - ' '
    - '&9Electrolytes'
    - '&7If you have &9Speed &7on kill, add &c2 &7seconds'
    - '&7to its duration, (Halved for Speed II+, Max 18s).'
  HEARTS:
    Lore:
    - ' '
    - '&9Hearts'
    - '&7Increase your max health by 0.5❤.' 
  TNT:
    Lore:
    - ' '
    - '&9TNT'
    - '&7Spawn with &c2 TNT&7. &cTNT'
    - '&7explodes after 1.5 seconds and' 
    - '&7deals &c1.5❤ &7in a 3 blocks radius.'
    - '&7Gain &c+2 TNT&7 on kill.'
  STRIKEGOLD:
    Lore:
    - ' '
    - '&9Strike Gold'
    - '&7Increase your max health by 0.5❤.'
  DOUBLEJUMP:
    Lore: 
    - ' '
    - '&dRARE! &9Double Jump'
    - '&7 You can double-jump. (20s cooldown).'
  ESCAPEPOD:
    Lore:
    - ' '
    - '&dRARE! &9Escape Pod'
    - '&7When hit below &c2❤&7, launch into the air dealing'
    - '&c1❤ &7damage to nearby enemies and gaining Regen III (20s).'
    - '&7Can launch once per life.'

#Ignore from this point on --------- end of config ###################
#                 _           ___                      ___ _         #
#                | |         / __)                    / __|_)        #
#  ____ ____   _ | |    ___ | |__     ____ ___  ____ | |__ _  ____   #
# / _  )  _ \ / || |   / _ \|  __)   / ___) _ \|  _ \|  __) |/ _  |  #
#( (/ /| | | ( (_| |  | |_| | |     ( (__| |_| | | | | |  | ( ( | |  #
# \____)_| |_|\____|   \___/|_|      \____)___/|_| |_|_|  |_|\_|| |  #
#                                                           (_____|  #
######################################################################
#
#
#
#
#
#
#
#
#
#
# Come here to change some plugin data, rest of the data is stored in data.yml
Top:
  Falcon:
    Kills: 1
# All blocks with an inventory or any blocks that when right clicked shouldn't equip armor. 
# - Curtousy of ArmorEquipEvent Library.
blocked:
    - FURNACE
    - CHEST
    - TRAPPED_CHEST
    - BEACON
    - DISPENSER
    - DROPPER
    - HOPPER
    - WORKBENCH
    - ENCHANTMENT_TABLE
    - ENDER_CHEST
    - ANVIL
    - BED_BLOCK
    - FENCE_GATE
    - SPRUCE_FENCE_GATE
    - BIRCH_FENCE_GATE
    - ACACIA_FENCE_GATE
    - JUNGLE_FENCE_GATE
    - DARK_OAK_FENCE_GATE
    - IRON_DOOR_BLOCK
    - WOODEN_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - WOOD_BUTTON
    - STONE_BUTTON
    - TRAP_DOOR
    - IRON_TRAPDOOR
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - REDSTONE_COMPARATOR_OFF
    - REDSTONE_COMPARATOR_ON
    - FENCE
    - SPRUCE_FENCE
    - BIRCH_FENCE
    - JUNGLE_FENCE
    - DARK_OAK_FENCE
    - ACACIA_FENCE
    - NETHER_FENCE
    - BREWING_STAND
    - CAULDRON
    - SIGN_POST
    - WALL_SIGN
    - SIGN
    - LEVER
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - LIME_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PINK_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - RED_SHULKER_BOX
    - SILVER_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - YELLOW_SHULKER_BOX